version: '3.8'

services:
  backend:
    build:
      context: https://github.com/issarion23/Industrial-AI-Ops.git
      dockerfile: Dockerfile
    container_name: industrial-ai-backend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=IndustrialAI;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - ModelsPath=/app/models
    volumes:
      - backend-models:/app/models
    depends_on:
      - db
    networks:
      - industrial-network

  frontend:
    build:
      context: https://github.com/issarion23/industrial-ai-ops-mvc.git
      dockerfile: Dockerfile
    container_name: industrial-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - industrial-network

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: industrial-ai-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - industrial-network


volumes:
  backend-models:
  mssql-data:

networks:
  industrial-network:
    driver: bridge
